# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rules:
  []
  #- matches:
  #    anyOf:
  #      - category: "Open Port"
  #        attributes:
  #          port: 21
  #          state: open
  #      - category: "Open Port"
  #        attributes:
  #          port: 389
  #          state: open
  #  override:
  #    severity: "high"
  #    description: "Telnet is bad"

hook:
  image:
    # hook.image.repository -- Hook image repository
    repository: docker.io/securecodebox/hook-finding-post-processing
    # hook.image.tag -- The image Tag defaults to the charts version if not defined.
    # @default -- defaults to the charts version
    tag: null

  # hook.ttlSecondsAfterFinished -- Seconds after which the kubernetes job for the hook will be deleted. Requires the Kubernetes TTLAfterFinished controller: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
  ttlSecondsAfterFinished: null
