# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "finding-post-processing.fullname" . }}
  labels:
    {{- include "finding-post-processing.labels" . | nindent 4 }}
spec:
  type: ReadAndWrite
  image: "{{ .Values.hook.image.repository }}:{{ .Values.hook.image.tag | default .Chart.Version }}"
  env:
    - name: RULES
      value: {{ .Values.rules | toJson | quote }}
