# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - MARKDOWN # Disable markdown as the readmes are generated automatically
  # - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD # standard is a javascript linter that by design can not be configured in any way. This project uses eslint anyways.
  - SPELL_CSPELL # disable cspell because if finds way to many false positives and it would be way to much work to exclude all false positives

SHOW_ELAPSED_TIME: true
DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

# ignore files generated by controller-gen
FILTER_REGEX_EXCLUDE: (.*rbac/role\.yaml|.*bases/.*\.yaml)
VALIDATE_ALL_CODEBASE: false
IGNORE_GENERATED_FILES: true

# disable useless alpaca ascii art that gets printed at the start of the linting
PRINT_ALPACA: false