apiVersion: "cascading.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "screenshooter-http-scan"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: light
spec:
  matches:
    anyOf:
      - category: "Open Port"
        attributes:
          service: http
          state: open
      - category: "Open Port"
        attributes:
          port: 80
          state: open
  scanSpec:
    scanType: "screenshooter"
    parameters: ["http://{{$.hostOrIP}}:{{attributes.port}}"]
