# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "zap-advanced-xml"
  labels:
    {{- include "zap.labels" . | nindent 4 }}
spec:
  image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parser.ttlSecondsAfterFinished }}
