apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-scripts-authentication
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
binaryData:
  {{- range $path, $d := .Files.Glob "scripts/authentication/*" }}
  {{ $path | base }}: |-
  {{- $d | toString | b64enc | nindent 4 }}
  {{ end }}