apiVersion: "cascading.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "gitleaks-scan"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: high
spec:
  matches:
    anyOf:
      - category: "Git Repository"
  scanSpec:
    scanType: "gitleaks"
    parameters:
      - "-r"
      - "{{attributes.web_url}}"
      #Provide a access token
      - "--access-token"
      - "<YOUR-GITLAB/GITHUB-TOKEN>"
      - "--config"
      - "/home/config_all.toml"

