apiVersion: v1
kind: Namespace
metadata:
  name: juice-shop
  annotations:
    auto-discovery.securecodebox.io/enabled: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: juice-shop
  labels:
    scm.securecodebox.io/branch: v12.6.1
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: juice-shop
  labels:
    app: juice-shop
spec:
  selector:
    matchLabels:
      app: juice-shop
  replicas: 1
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop:v12.6.1
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zap
  namespace: juice-shop
spec:
  chart:
    repository: https://charts.securecodebox.io
    version: 2.4.0
    name: zap
# ---
# apiVersion: helm.fluxcd.io/v1
# kind: HelmRelease
# metadata:
#   name: persistence-defectdojo
#   namespace: juice-shop
# spec:
#   chart:
#     git: https://github.com/secureCodeBox/secureCodeBox.git
#     ref: feature/defect-dojo
#     path: hooks/persistence-defectdojo
#   values:
#     defectdojo:
#       auth:
#         apiKey: e2ed466e0f85127d08879c178ec8ec8df3a15452