# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "ncrack-xml"
spec:
  image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parser.image.ttlSecondsAfterFinished }}
  env: 
    {{- toYaml .Values.parser.env | nindent 4 }}
  {{- if .Values.encryptPasswords.existingSecret }}
  - name: "ENCRYPTION_KEY_LOCATION"
    value: "/secrets/{{ .Values.encryptPasswords.key }}"
  volumes:
  - name: "ncrack-secret"
    secret:
      secretName: {{ .Values.encryptPasswords.existingSecret }}
  volumeMounts:
  - name: "ncrack-secret"
    mountPath: "/secrets/"
  {{- end }}
