apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "ncrack-xml"
spec:
  handlesResultsType: ncrack-xml
  image: "{{ .Values.parserImage.registry }}/{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag }}"
