# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "cascading.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "gitleaks-gitlab-scan-public"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: medium
spec:
  matches:
    anyOf:
      - name: "GitLab Repo"
        attributes:
          visibility: public
  scanSpec:
    scanType: "gitleaks"
    parameters:
      - "-r"
      - "{{{location}}}"
      - "--config"
      - "/home/config_all.toml"
      #Provide an access token
      - "--access-token"
      - "$(GITLAB_TOKEN)"
    env:
      - name: GITLAB_TOKEN
        valueFrom:
          secretKeyRef:
            name: gitlab-access-token
            key: token

