apiVersion: "cascading.securecodebox.io/v1"
kind: CascadingRule
metadata:
  name: "gitleaks-github-scan-public"
  labels:
    securecodebox.io/invasive: non-invasive
    securecodebox.io/intensive: medium
spec:
  matches:
    anyOf:
      - name: "GitHub Repo"
        attributes:
          visibility: public
  scanSpec:
    scanType: "gitleaks"
    parameters:
      - "-r"
      - "{{{attributes.web_url}}}"
      - "--config"
      - "/home/config_all.toml"
      - "--access-token"
      - "$(GITHUB_TOKEN)"
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-access-token
            key: token

