apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    {{ .Values.serviceAccount.annotations | toYaml | indent 4}}
  labels:
    {{ .Values.serviceAccount.labels | toYaml | indent 4 }}