parserImage:
  repository: docker.io/scbexperimental/parser-nmap
  # parserImage.tag - defaults to the charts version
  tag: null

scannerJob:
  resources: {}
# scannerJob:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "250m"
#     limits:
#       memory: "512Mi"
#       cpu: "500m"
