parserImage:
  registry: docker.io
  repository: scbexperimental/parser-wpscan
  tag: latest

scannerJob:
  resources: {}
# scannerJob:
#   resources:
#     requests:
#       memory: "256Mi"
#       cpu: "250m"
#     limits:
#       memory: "512Mi"
#       cpu: "500m"
