# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: whatweb
description: A Helm chart for the whatweb security Scanner that integrates with the secureCodeBox.

type: application
# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v3.1.0-alpha1
appVersion: v0.5.5
kubeVersion: ">=v1.11.0-0"

keywords:
  - security
  - whatweb
  - scanner
  - secureCodeBox
home: https://docs.securecodebox.io/docs/scanners/Whatweb
icon: https://docs.securecodebox.io/img/integrationIcons/Whatweb.svg
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: iteratec GmbH
    email: secureCodeBox@iteratec.com
