parserImage:
  repository: docker.io/scbexperimental/parser-ncrack
  # parserImage.tag - defaults to the charts version
  tag: null

scannerJob:
  ttlSecondsAfterFinished: null
  resources: {}
  extraVolumes: []
  extraVolumeMounts: []
