apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "test-txt"
spec:
  image: "{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parseJob.ttlSecondsAfterFinished }}
