# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "nikto-json"
spec:
  image: "{{ .Values.parser.repository }}:{{ .Values.parser.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parser.ttlSecondsAfterFinished }}
