# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: cmseek-example
spec:
  scanType: "cmseek"
  parameters:
    - "-u"
    - "https://www.joomla.example.com" # Change to the website you want to scan