apiVersion: "execution.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "kubeaudit"
spec:
  extractResults:
    type: kubeaudit-jsonl
    location: "/home/securecodebox/kubeaudit.jsonl"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubeaudit
              image: "securecodebox/scanner-kubeaudit:{{ .Chart.AppVersion }}"
              command:
                - "sh"
                - "/wrapper.sh"
                - "all"
                - "--exitcode"
                - "0"
                - "--format"
                - "json"
              resources:
                {{- toYaml .Values.scannerJob.resources | nindent 16 }}
          serviceAccountName: kubeaudit
