# SPDX-FileCopyrightText: 2020 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "kubeaudit{{ .Values.scanner.nameAppend | default ""}}"
spec:
  extractResults:
    type: kubeaudit-jsonl
    location: "/home/securecodebox/kubeaudit.jsonl"
  jobTemplate:
    spec:
      {{- if .Values.scanner.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.scanner.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.scanner.backoffLimit }}
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kubeaudit
              image: "securecodebox/scanner-kubeaudit:{{ .Chart.AppVersion }}"
              command:
                - "sh"
                - "/wrapper.sh"
                - "all"
                - "--exitcode"
                - "0"
                - "--format"
                - "json"
              resources:
                {{- toYaml .Values.scanner.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.scanner.securityContext | nindent 16 }}
              env:
                {{- toYaml .Values.scanner.env | nindent 16 }}
              volumeMounts:
                {{- toYaml .Values.scanner.extraVolumeMounts | nindent 16 }}
            {{- if .Values.scanner.extraContainers }}
            {{- toYaml .Values.scanner.extraContainers | nindent 12 }}
            {{- end }}
          volumes:
            {{- toYaml .Values.scanner.extraVolumeMounts | nindent 12 }}
          serviceAccountName: kubeaudit
