apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "kubeaudit-jsonl"
spec:
  handlesResultsType: kubeaudit-jsonl
  image: "{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag | default .Chart.Version }}"
