apiVersion: v2
name: declarative-subsequent-scans
description: Starts possible subsequent security scans based on findings (e.g. open ports found by NMAP or subdomains found by AMASS).

type: application

# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v2.6.0-alpha1
kubeVersion: ">=v1.11.0-0"

keywords:
  - security
  - secureCodeBox
  - hook
home: https://docs.securecodebox.io/docs/hooks/cascading-scans
icon: https://docs.securecodebox.io/img/integrationIcons/Cascading Scans.svg
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: iteratec GmbH
    email: secureCodeBox@iteratec.com

dependencies: []

