# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/scbexperimental/hook-declarative-subsequent-scans
  # image.tag - defaults to the charts version
  tag: null
