apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "teams-webhook.fullname" . }}
spec:
  type: ReadOnly
  {{- if .Values.image.digest }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}@{{ .Values.image.digest }}"
  {{- else }}
  image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  {{- end }}
  env:
    - name: WEBHOOK_URL
      value: {{ .Values.webhookUrl | quote }}
    - name: VULNMANAG_ENABLED
      value: {{ .Values.vulnerabilitymanagement.enabled | quote }}
    - name: VULNMANAG_NAME
      value: {{ .Values.vulnerabilitymanagement.name | quote }}
    - name: VULNMANAG_DASHBOARD_URL
      value: {{ .Values.vulnerabilitymanagement.url | quote }}
    - name: VULNMANAG_DASHBOARD_FINDINGS_URL
      value: {{ .Values.vulnerabilitymanagement.findingsurl | quote }}
