apiVersion: v2
name: test-scan
description: A Helm chart to test the secureCodeBox operator

type: application
# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v2.6.0-alpha1

keywords:
  - security
  - scanner
  - secureCodeBox
  - integrationTest
  - test
sources:
  - https://github.com/secureCodeBox/secureCodeBox
maintainers:
  - name: iteratec GmbH
    email: securecodebox@iteratec.com
