apiVersion: "execution.securecodebox.io/v1"
kind: ScanType
metadata:
  name: "typo3scan"
spec:
  extractResults:
    type: typo3scan-json
    location: "/home/securecodebox/typo3scan-results.json"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: typo3scan
              image: "{{ .Values.scanner.image.repository }}:{{ .Values.scanner.image.tag | default .Chart.AppVersion }}"
              command:
                - "sh"
                - "/home/typo3scan/Typo3Scan/wrapper.sh" 
                - "--no-interaction"
                - "--json"