apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "acstis-log"
spec:
  handlesResultsType: acstis-log
  image: "{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.parseJob.ttlSecondsAfterFinished }}
