apiVersion: "execution.securecodebox.io/v1"
kind: ScanCompletionHook
metadata:
  name: {{ include "generic-webhook.fullname" . }}
spec:
  type: ReadOnly
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
  ttlSecondsAfterFinished: {{ .Values.hookJob.ttlSecondsAfterFinished }}
  env:
    - name: WEBHOOK_URL
      value: {{ .Values.webhookUrl | quote }}
  {{- if .Values.customCACertificate.existingCertificate }}
  volumes:
    - name: ca-certificate-dir
      configMap:
        name: {{ .Values.customCACertificate.existingCertificate }}
  
  volumeMounts:
    - name: ca-certificate-dir
      mountPath: /etc/ssl/certs/{{ .Values.customCACertificate.certificate }}
  {{- end }}
