apiVersion: v2
name: operator
description: secureCodeBox Operator to automate the execution of security scans on kubernetes

type: application

# version - gets automatically set to the secureCodeBox release version when the helm charts gets published
version: v2.0.0-alpha1

dependencies:
  - name: minio
    version: 5.0.19
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: minio.enabled
