# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "nuclei-example-scan"
spec:
  scanType: "nuclei"
  parameters:
    # Target domain name of the finding and start a nuclei scan
    - "-u"
    - "example.com"
