# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Default values for dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hook:
  image:
    # hook.image.repository -- Hook image repository
    repository: docker.io/securecodebox/hook-notification
    # hook.image.tag -- Image tag
    # @default -- defaults to the charts version
    tag: null
    # -- Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
    pullPolicy: IfNotPresent

  # hook.labels -- Add Kubernetes Labels to the hook definition
  labels: {}

  # hook.ttlSecondsAfterFinished -- seconds after which the kubernetes job for the hook will be deleted. Requires the Kubernetes TTLAfterFinished controller: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
  ttlSecondsAfterFinished: null

notificationChannels:
  - name: slack
    type: slack
    template: slack-messageCard
    rules:
      - matches:
          anyOf:
            - category: "Open Port"
    endPoint: SOME_ENV_KEY

customTemplateMap:
  exists: false
  name: config-map-name

env:
  - name: SOME_ENV_KEY
    valueFrom:
      secretKeyRef:
        name: some-secret
        key: some-key
  - name: SMTP_CONFIG
    valueFrom:
      secretKeyRef:
        name: some-secret
        key: smtp-config-key
