apiVersion: "execution.experimental.securecodebox.io/v1"
kind: ScanType
metadata:
  name: {{ .Release.Name }}
spec:
  extractResults:
    type: nmap-xml
    location: "/home/securecodebox/nmap-results.xml"
  jobTemplate:
    spec:
      {{- if .Values.scannerJob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.scannerJob.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nmap
              image: scbexperimental/nmap:7.80
              command: ["nmap", "-oX", "/home/securecodebox/nmap-results.xml"]
              env:
                {{- toYaml .Values.scannerJob.env | nindent 16 }}
              resources:
                {{- toYaml .Values.scannerJob.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.scannerJob.securityContext | nindent 16 }}
