apiVersion: "execution.securecodebox.io/v1"
kind: ParseDefinition
metadata:
  name: "git-repo-scanner-json"
spec:
  handlesResultsType: git-repo-scanner-json
  image: "{{ .Values.parserImage.repository }}:{{ .Values.parserImage.tag | default .Chart.Version }}"
