name: "CI"
on: push
jobs:
  parser-sdk:
    name: "Build | Parser SDK"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_NAMESPACE }}/parser-sdk-nodejs
          tag-sha: true
          tag-custom: ci-local
          tag-semver: |
            {{ version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./parser-sdk/nodejs
          file: ./parser-sdk/nodejs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}


   hook-sdk:
     name: "Build | Hook SDK"
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Docker Meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           image: ${{ secrets.DOCKER_NAMESPACE }}/hook-sdk-nodejs
           tag-sha: true
           tag-semver: |
             {{ version }}

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and Push
         uses: docker/build-push-action@v2
         with:
           context: ./hook-sdk/nodejs
           file: ./hook-sdk/nodejs
           platforms: linux/amd64
           push: true
           tags: ${{ steps.docker_meta.outputs.tags }}
           labels: ${{ steps.docker_meta.outputs.labels }}
