# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: "Update Helm Docs"

on:
  push:

jobs:
  helm-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_COMMITS_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_COMMITS_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Download Helm Docs
        run: |
          mkdir helm-docs
          cd helm-docs

          curl --output helm-docs.tar.gz --location https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz
          # Checksum must be extracted from the checksum file every time helm-docs gets updated.
          echo "a352e13a8438045b8ed138b821cb757c177acd999c1af77345152d7a64b0ddb7  helm-docs.tar.gz" | shasum --check

          tar -xvf helm-docs.tar.gz
          # Verify installation
          ./helm-docs --version

          sudo mv helm-docs /usr/local/bin/helm-docs

      - name: Generate README
        run: |
          # Generate README.md based on Chart.yaml and template
          make readme
      - name: Generate Demo-Apps Docs
        run: |
          # Start in the hooks folder
          cd demo-targets
          # https://github.com/koalaman/shellcheck/wiki/SC2044
          find . -type f -name Chart.yaml -print0 | while IFS= read -r -d '' chart; do
          (
            dir="$(dirname "${chart}")"
            echo "Processing Helm Chart in $dir"
            cd "${dir}" || exit
            if [ -d "docs" ]; then
              echo "Docs Folder found at: ${dir}/docs"
              helm-docs --template-files=./../../.helm-docs/templates.gotmpl --template-files=.helm-docs.gotmpl --template-files=./../../.helm-docs/README.DockerHub-Target.md.gotmpl --output-file=docs/README.DockerHub-Target.md
              helm-docs --template-files=./../../.helm-docs/templates.gotmpl --template-files=.helm-docs.gotmpl --template-files=./../../.helm-docs/README.ArtifactHub.md.gotmpl --output-file=docs/README.ArtifactHub.md
            else
              echo "Ignoring Docs creation process for Chart $dir, because no `docs` folder found at: ${dir}/docs"
            fi
          )
          done

      - name: Generate Docker Hooks Docs
        run: make hook-docs

      - name: Generate Docker Scanner Docs
        run: make scanner-docs

      - name: Generate Operator Docs
        run: make operator-docs

      - name: Generate AutoDiscovery Docs
        run: make auto-discovery-docs

      - name: Remove Helm Docs Files
        run: |
          # Remove helm-docs download to ensure they don't get committed back
          rm -rf helm-docs

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Updating Helm Docs
          commit_user_email: securecodebox@iteratec.com
          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--signoff'
