name: Check outdated scanners
on:
  push:
#  schedule:
#    - cron: "0 8 * * *"
jobs:
  version-compare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scanner:
          - amass
          - angularjs-csti-scanner
          - gitleaks
          - kube-hunter
          - kubeaudit
          - ncrack
          - nuclei
          - ssh-scan
          - sslyze
          - trivy
          - typo3scan
          - whatweb
          - wpscan
          - zap
          - zap-advanced 
          # missing scanners are : nmap   
    steps:
      - uses: actions/checkout@v2

      - name: Fetch scanner's version API
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: echo versionApi=$(yq e .versionApi scanners/${{ matrix.scanner }}/Chart.yaml) >> $GITHUB_ENV 

      - name: Fetch release version
        run: echo release=$((curl -sL ${{env.versionApi}}  ) | jq -r ".tag_name") >> $GITHUB_ENV
            
      - name: Fetch local scanner version
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: echo local=$(yq e .appVersion scanners/${{ matrix.scanner }}/Chart.yaml) >> $GITHUB_ENV

      - name: Check if outdated  
        if: ${{ env.release != env.local }}          
        run: echo '${{ matrix.scanner }} scanner is outdated.  scB version is ${{env.local}} and remote version is ${{env.release}}'
        #TODO Pull request to update scanner   