name: Check outdated scanners
on:
  push:
#  schedule:
#    - cron: "0 8 * * *"
jobs:
  version-compare:
    runs-on: ubuntu-latest
    # env:
    #   local: 1
    #   release: 2
    strategy:
      matrix:
        scanner:
          - amass
          - angularjs-csti-scanner
          - gitleaks
          - kube-hunter
          - kubeaudit
          - ncrack
          - nuclei
          - ssh-scan
          - sslyze
          - trivy
          - whatweb
          - wpscan
          - zap
          - zap-advanced 
          # missing scanners are : nmap, nikto, typo3scan
    steps:
      - uses: actions/checkout@v2

      - name: Fetch scanner's version API
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: echo versionApi=$(yq e .versionApi scanners/${{ matrix.scanner }}/Chart.yaml) >> $GITHUB_ENV 

      - name: Fetch release version
        run: echo release=$((curl -sL ${{env.versionApi}}  ) | jq -r ".tag_name") | tr -d "v" >> $GITHUB_ENV
            
      - name: Fetch local scanner version
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: echo local=$(yq e .appVersion scanners/${{ matrix.scanner }}/Chart.yaml) | tr -d "v" >> $GITHUB_ENV

      - name: Check if outdated  
        if: ${{ env.release != env.local }}          
        run: |
          echo '${{ matrix.scanner }} scanner is outdated.  scB version is ${{env.local}} and remote version is ${{env.release}}'
          echo "pr=[sCB-Bot] Upgraded ${{ matrix.scanner }} from ${{env.local}} to ${{env.release}}" >> $GITHUB_ENV
          echo prExists=$(curl -sL https://api.github.com/repos/secureCodeBox/secureCodeBox/pulls | jq '.[]' | grep "${{env.pr}}" -c) >> $GITHUB_ENV 

      - name : Upgrade Scanner
        if: ${{ env.release != env.local && env.prExists == 0 }} 
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: yq e '.appVersion = ${{env.release}}' ./scanners/${{ matrix.scanner }}/Chart.yaml >> ./scanners/${{ matrix.scanner }}/Chart.yaml

